### ISSUE TITLE
Missing informartion about used namespace in tutorial

### ISSUE THREAD

**Issue by dakur** [jkuchar/FileDownloader#12]
On http://addons.nette.org/jkuchar/filedownloader there is no information about the used namespace FileDownloader. When adding to config.neon, I've tried just
- FileDownload
and it took me some time to find out that there should be:
- FileDownloader\FileDownload
instead.

**Comment by jkuchar** [comment]
Fixed: https://github.com/jkuchar/FileDownloader/commit/5a66625c02efabaf5dd0e74f43eed0156143b3be

Could be closed?

**Comment by dakur** [comment]
Yes. :-)
