### ISSUE TITLE
Environment:: uses

### ISSUE THREAD

**Issue by dakur** [jkuchar/FileDownloader#13]
Isn't it deprecated now?
(FDTools.php)

**Comment by jkuchar** [comment]
Definitely is. This part of library is quite old (originally written for Nette 0.9). PRs are welcome! :-)

**Comment by jkuchar** [comment]
This class is living from 2009 :-) https://github.com/jkuchar/FileDownloader/commits/master/FileDownloader/FDTools.php

**Comment by jkuchar** [comment]
Also if you see anywhere anything in Czech, don't be afraid to translate it.

**Comment by jkuchar** [comment]
fixed in master
