### ISSUE TITLE
Error Nette\Environment requires constant TEMP_DIR

### ISSUE THREAD

**Issue by eljodedor21** [jkuchar/FileDownloader#15]
Hi, sorry for my questions but i tried for use the repositroy and ever show me this error Nette\Environment requires constant TEMP_DIR ,  i use symfony 2 framework

**Comment by jkuchar** [comment]
Nette environment dependency is a little hell of this library. I accepting PR on this. (removing nette\environment dependency)

I'll take a look at it on monday.

**Comment by eljodedor21** [comment]
now I show me  this error
Fatal error: Class 'Nette\Environment' not found in C:\wamp\www\nvr\vendor\jkuchar\filedownloader\FileDownloader\BaseFileDownload.php on line 531

**Comment by jkuchar** [comment]
Please try to execute `composer require nette/deprecated` (quick&dirty fix for now)

**Comment by lukyrys** [comment]
Any news on this?

**Comment by jkuchar** [comment]
Would you mind finishing #19?

**Comment by jkuchar** [comment]
there is no environment used anymore in master
