### ISSUE TITLE
How can I set my custom headers?

### ISSUE THREAD

**Issue by HamedGh** [jkuchar/FileDownloader#17]
I found that FileDownloadRunnable class have a addHeader() method, but I can't figure out how to use it!

**Comment by jkuchar** [comment]
FileDownloadRunnable? Where, what?

You can always add headers by binding event before content sent and adding header to HttpResponse (->setHeader)

**Comment by HamedGh** [comment]
could give me an example?

**Comment by jkuchar** [comment]
https://github.com/jkuchar/FileDownloader/blob/master/README.md#callbacks

BeforeOutputStarts
