### ISSUE TITLE
Missing BigFilesTools

### ISSUE THREAD

**Issue by Jam3si** [jkuchar/FileDownloader#7]
FileDownloader is missing BigFileTools, have to download it extra. But after that, method onComplete do not work on nette 2.2

**Comment by jkuchar** [comment]
Which file downloader do you use?

**Comment by Jam3si** [comment]
master - 1.2.0

**Comment by jkuchar** [comment]
I had different thing on mind, AdvancedDownloader or Simple?

**Comment by Jam3si** [comment]
Oh, AdvancedDownloader

**Comment by jkuchar** [comment]
On complete is called from https://github.com/jkuchar/FileDownloader/blob/master/FileDownloader/BaseFileDownload.php download() method. Could you please try to debug, why your script didn't reach onComplete() call? There must be some exception thrown...

**Comment by jkuchar** [comment]
OnComplete is called when whole file has been downloaded, isn't that problem?

**Comment by jkuchar** [comment]
fixed in master
