### ISSUE TITLE
Parsing PHP ini value for memory limit can’t handle -1

### ISSUE THREAD

**Issue by dasim** [jkuchar/FileDownloader#9]
If I have no limit set for memory (value = `-1`), I get InvalidStateException("Can't parse php ini value!").

The line in here: https://github.com/jkuchar/FileDownloader/blob/master/FileDownloader/FDTools.php#L102

I’m not sure what is a reasonable return value for such case, otherwise I’d make a PR since it’s an easy change.

**Comment by jkuchar** [comment]
How exactly looks your memory limit settings?
(if there is just 0) It should be caught by 
if ($phpIniValueInt == 0) {
return 0;
}



10. 3. 2015 v 3:45, Dalibor Simacek <notifications@github.com>:

**Comment by dasim** [comment]
memory_limit = -1

**Comment by jkuchar** [comment]
Isn't correct value 0 for no memory limit? (handled by those 3 lines I posted before) Surely if -1 is also correct value for unlimitied (please add here ref to PHP Doc, thanks), please send PR. 



10. 3. 2015 v 9:30, Dalibor Simacek <notifications@github.com>:

**Comment by dasim** [comment]
> Note that to have no memory limit, set this directive to -1.

http://php.net/manual/en/ini.core.php#ini.memory-limit

There’s no mention what `0` means and I didn’t know it might mean unlimited as well.

**Comment by jkuchar** [comment]
Probably it was written in older versions of PHP in php.ini file.

From this point of view, I think it means that code fragment mentioned before should change to 

if ($phpIniValueInt <= 0) { return 0; }

TODO: Refactoring: return self::MEMORY_UNLIMITED constant (it can still be zero for compatibility reasons, but current state is sort of magic)

10. 3. 2015 v 9:56, Dalibor Simacek <notifications@github.com>:

**Comment by jkuchar** [comment]
closed by #10
